=== aselimovic/mw-api/src/main/resources/raml/schemas/binding-entities.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "name": "BindingEntity set",
  "type": "array",
  "items": {
    "name": "BindingEntity",
    "type": "object",
    "properties": {
      "bindingEntityId": { "type": "integer", "required": true },
      "systemId": { "type": "string", "maxLength": 15 },
      "password": { "type": "string", "maxLength": 8 },
      "systemType": { "type": "string", "maxLength": 13 },
      "description": { "type": "string", "maxLength": 255 }
    }
  }
}

=== aselimovic/mw-api/target/classes/raml/examples/binding-entities.json
[
  {
    "bindingEntityId": 1,
    "systemId": "systemId1",
    "password": "password1",
    "systemType": "systemType1",
    "description": "description1"
  },
  {
    "bindingEntityId": 2,
    "systemId": "systemId2",
    "password": "password2",
    "systemType": "systemType2",
    "description": "description2"
  },
  {
    "bindingEntityId": 3,
    "systemId": "systemId3",
    "password": "password3",
    "systemType": "systemType3",
    "description": "description3"
  }
]
